version: 2
jobs:
  build_and_deploy:
    docker:
      - image: registry.dev.brainhub.pl/tools/rancher-circleci
        auth:
          username: $HARBOR_USER
          password: $HARBOR_PASSWORD
    working_directory: ~/node-hello-world
    steps:
      - checkout
      - setup_remote_docker
      - run: docker --version
      - run: docker login -u $HARBOR_USER -p $HARBOR_PASSWORD registry.dev.brainhub.pl
      - run: docker build -t registry.dev.brainhub.pl/hello-world/node-hello-world .
      - run: docker push registry.dev.brainhub.pl/hello-world/node-hello-world:latest
      - run: rancher-compose --project-name hello-world --verbose up -d --force-upgrade --pull --confirm-upgrade node-hello-world

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
