version: 2
jobs:
  test:
    docker:
      - image: registry.dev.brainhub.pl/tools/rancher-circleci
        auth:
          username: $HARBOR_USER
          password: $HARBOR_PASSWORD
      working_directory: ~/node-hello-world
      steps:
        - checkout
        - setup_remote_docker
        - run: docker login -u $HARBOR_USER -p $HARBOR_PASSWORD registry.dev.brainhub.pl
        - run: docker build -t registry.dev.brainhub.pl/hello-world/node-hello-world .
        - run: docker run --rm --name node-hello-world --entrypoint '/bin/sh' registry.dev.brainhub.pl/hello-world/node-hello-world -c 'npm run lint'
  build_and_deploy:
    docker:
      - image: registry.dev.brainhub.pl/tools/rancher-circleci
        auth:
          username: $HARBOR_USER
          password: $HARBOR_PASSWORD
    working_directory: ~/node-hello-world
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $HARBOR_USER -p $HARBOR_PASSWORD registry.dev.brainhub.pl
      - run: docker build -t registry.dev.brainhub.pl/hello-world/node-hello-world .
      - run: docker push registry.dev.brainhub.pl/hello-world/node-hello-world:latest
      - run: rancher-compose --project-name node-hello-world --verbose up -d --force-upgrade --pull --confirm-upgrade node-hello-world

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              only: master
